-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analysis_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  persona_id uuid,
  score_attention integer,
  score_interest integer,
  score_desire integer,
  score_action integer,
  dominant_emotion text,
  reaction_fast text,
  reaction_slow text,
  final_verdict text,
  will_buy boolean,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  visual_impact_note text,
  audio_impact_note text,
  economic_context_given text,
  channel_context_given text,
  CONSTRAINT analysis_results_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_results_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT analysis_results_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.campaign_optimizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  better_slogan_idea text,
  visual_concept_idea text,
  psychological_trigger_advice text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  pomelli_prompt text,
  opt_name text,
  opt_objective text,
  opt_brand_tone text,
  opt_call_to_action text,
  opt_value_proposition text,
  opt_media_url text,
  opt_audience text,
  opt_brand_guidelines text,
  opt_channels text,
  economic_sentiment_at_optimization text,
  CONSTRAINT campaign_optimizations_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_optimizations_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  objective text NOT NULL,
  ad_slogan text,
  media_url text,
  media_type text,
  intended_audience_desc text,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  channel_type text DEFAULT 'DISPLAY'::text,
  brand_tone text,
  value_proposition text,
  call_to_action text,
  brand_guidelines text,
  is_ai_optimized boolean DEFAULT false,
  original_campaign_id uuid,
  macro_snapshot_id uuid,
  trend_snapshot_id uuid,
  trend_risk_score integer DEFAULT 0,
  trend_risk_analysis text,
  media_analysis_visual jsonb,
  media_analysis_transcript text,
  media_duration_seconds integer,
  media_analysis_status text DEFAULT 'pending'::text,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT campaigns_original_campaign_id_fkey FOREIGN KEY (original_campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaigns_macro_snapshot_id_fkey FOREIGN KEY (macro_snapshot_id) REFERENCES public.macro_economic_snapshots(id),
  CONSTRAINT campaigns_trend_snapshot_id_fkey FOREIGN KEY (trend_snapshot_id) REFERENCES public.cultural_trend_snapshots(id)
);
CREATE TABLE public.cultural_trend_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date timestamp with time zone DEFAULT now(),
  trending_topics jsonb,
  societal_mood text,
  risk_level integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  brand_safety_status text,
  recommended_ad_tone text,
  CONSTRAINT cultural_trend_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.macro_economic_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE UNIQUE,
  cpi_annual_pct numeric,
  ppi_annual_pct numeric,
  usd_try_rate numeric,
  eur_try_rate numeric,
  policy_rate_pct numeric,
  consumer_confidence_idx numeric,
  unemployment_rate_pct numeric,
  real_purchasing_power text DEFAULT 'orta'::text CHECK (real_purchasing_power = ANY (ARRAY['cok_dusuk'::text, 'dusuk'::text, 'orta'::text, 'yuksek'::text, 'cok_yuksek'::text])),
  economic_sentiment text DEFAULT 'duragan'::text CHECK (economic_sentiment = ANY (ARRAY['kriz'::text, 'daralma'::text, 'duragan'::text, 'buyume'::text, 'canlanma'::text])),
  source text DEFAULT 'TCMB_EVDS'::text,
  raw_response jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT macro_economic_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  age integer NOT NULL,
  gender text,
  job_title text,
  location text,
  big_five_traits jsonb NOT NULL,
  primary_archetype text,
  shopping_drivers ARRAY,
  bio_summary text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  preferred_channels ARRAY DEFAULT '{}'::text[],
  ses_group character varying,
  life_stage character varying,
  vals_segment character varying,
  neuro_trigger character varying,
  b2b_segment character varying,
  economic_sensitivity jsonb DEFAULT '{"recession_behavior": "cautious", "spending_elasticity": "moderate", "interest_rate_impact": 50, "inflation_sensitivity": 50, "exchange_rate_awareness": 50}'::jsonb,
  monthly_income_band text DEFAULT 'orta'::text CHECK (monthly_income_band = ANY (ARRAY['cok_dusuk'::text, 'dusuk'::text, 'orta'::text, 'orta_ustu'::text, 'yuksek'::text, 'cok_yuksek'::text])),
  CONSTRAINT personas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  company_name text,
  industry text,
  subscription_plan text DEFAULT 'free'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  email text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.segment_personas (
  segment_id uuid NOT NULL,
  persona_id uuid NOT NULL,
  CONSTRAINT segment_personas_pkey PRIMARY KEY (segment_id, persona_id),
  CONSTRAINT segment_personas_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.segments(id),
  CONSTRAINT segment_personas_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text,
  icon text,
  color_theme text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  user_id uuid,
  CONSTRAINT segments_pkey PRIMARY KEY (id),
  CONSTRAINT segments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
